! this is a generated file, DO NOT EDIT UNLESS YOU KNOW WHAT YOU ARE DOING
Abbreviate ". ";
Abbreviate ", ";
Abbreviate "ing ";
Abbreviate "the ";
Abbreviate "The";
Abbreviate "You ";
Abbreviate "tion";
Abbreviate "to ";
Abbreviate "have ";
Abbreviate "'t ";
Abbreviate "achieve";
Abbreviate "and ";
Abbreviate "you ";
Abbreviate "**]";
Abbreviate "ould";
Abbreviate "civil protec";
Abbreviate "hat ";
Abbreviate "re ";
Abbreviate "_obj)";
Abbreviate "(first ";
Abbreviate "in ";
Abbreviate " on";
Abbreviate " someth";
Abbreviate "and";
Abbreviate "ing";
Abbreviate " with";
Abbreviate " pr";
Abbreviate "object";
Abbreviate " not";
Abbreviate " be";
Abbreviate "ave";
Abbreviate " of";
Abbreviate " as";
Abbreviate " se";
Abbreviate " is";
Abbreviate " it";
Abbreviate " un";
Abbreviate "closed";
Abbreviate " here";
Abbreviate " this";
Abbreviate "Prospekt";
Abbreviate " look";
Abbreviate "already";
Abbreviate " door";
Abbreviate " game";
Abbreviate " st";
Abbreviate " you";
Abbreviate "This";
Abbreviate "citizen";
Abbreviate " for";
Abbreviate " has";
Abbreviate "You";
Abbreviate "coveralls";
Abbreviate " inter";
Abbreviate "Not";
Abbreviate "was";
Abbreviate " say";
Abbreviate "City 1";
Abbreviate ".^^";
Abbreviate " su";
Abbreviate " or";
Abbreviate "open";
Abbreviate "lock";
Abbreviate " com";
